[workspace]
resolver = "2"
members = [
    "broker",
    "client",
    "storage",
    "query",
    "common",
    "client",
    "common"]

[workspace.dependencies]
common = { path = "common" }

anyhow = "1.0.104"
tokio = { version = "1.53.1", features = ["net", "macros", "rt-multi-thread", "io-util", "time"] }
rustls = "0.23.43"
tokio-rustls = "0.26.4"
tokio-util = "0.7.19"